
services:

  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME} # Replace with your database
      MYSQL_USER: ${DB_USER} # Replace with your user
      MYSQL_PASSWORD: ${DB_PASSWORD} # Replace with your password
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount the SQL file
    ports:
      - "3306:3306"
    networks:
      - mariadb_network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb  
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      PMA_USER: ${DB_USER}  # Add your login username here
      PMA_PASSWORD: ${DB_PASSWORD}  # Add your login password here
    depends_on:
      - mariadb
    networks:
      - mariadb_network

networks:
  mariadb_network:
