
services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER} # Replace with your user
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}  # Replace with your password

# use mongo-composs for client
